### ISSUE TITLE
savollar

### ISSUE THREAD

**Issue by Kamezukash1** [HaydarovAkbar/SSPproposalbot#1]
proyektdan shablon olsam bo'ladimi

**Comment by Akbarprogramer1** [comment]
yoq ))

**Comment by HaydarovAkbar** [comment]
yoq !)

**Comment by Ravshanbek1006** [comment]
> proyektdan shablon olsam bo'ladimi

kimdan

**Comment by r-shamsiyev** [comment]
> > proyektdan shablon olsam bo'ladimi
> 
> kimdan

пройект эгасидан
